apiVersion: v1
kind: Service
metadata:
  name: springboot-demo-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8082
      nodePort: 30008   # NodePort 范围 30000-32767
  selector:
    app: springboot-demo